### ISSUE TITLE
the problem using cRegulome function:get_mir

### ISSUE THREAD

**Issue by loostchen** [ropensci/cRegulome#5]
> library(cRegulome)
> library(RSQLite)
> library(ggplot2)
> fl <- system.file('extdata', 'cRegulome.db', package = 'cRegulome')
> conn <- dbConnect(SQLite(), fl)
> dat <- get_mir(conn, mir = 'hsa-let-7g')
**error: Condition message must be a string**
The problem occured as followed.
I just follow the vignettes as given.

**Comment by MahShaaban** [comment]
A quick search with the error message suggests that it might be because of not loading the package `dbplyr`, so I suggest you do the following:
```
library(cRegulome)
library(RSQLite)
library(ggplot2)
library(dbplyr)

fl <- system.file('extdata', 'cRegulome.db', package = 'cRegulome')
conn <- dbConnect(SQLite(), fl)

dat <- get_mir(conn, mir = 'hsa-let-7g')
```
Notice the additional 4th line. This should load the `dbplyr` package if it's installed on your machine. If not, you can install it first using `install.packages('dbplyr')` then run the previous code.
